### ISSUE TITLE
/money top [number]

### ISSUE THREAD

**Issue by SimSonic** [niccholaspage/Fe#14]
where number is optional parameter to limit how many oligarchs show, defaulting to 5 or 10.

**Comment by SimSonic** [comment]
Is it possible to realize? I don't know Java so it is problem for me to fork repository and do it myself.

**Comment by niccholaspage** [comment]
Sorry. I've been pretty busy. I could implement this but it might take a bit because I'll need to limit the amount of top accounts you can see. I'd also need to add in pages for more than around 10 accounts.

**Comment by SimSonic** [comment]
I believe it should be simple task, just for pages add LIMIT with 'offset' in query:
SELECT \* FROM `{database}`.`{table}`
ORDER BY `money` DESC
LIMIT 10 \* {page}, 10;
