### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by borncorp** [niccholaspage/Fe#15]
I am using Fe in a server with over 50 players online. Whenever they buy stuff from the shops it lags the server. This is because they spam the signs or showcases to shop. I have tested this with essentialsshop and showcasestandalone. 

This issue is bad, it gets to the point where all player disconnects because their client  dont get any info because of the lag

**Comment by niccholaspage** [comment]
Yeah, this occurs because an SQL query occurs every time a balance changes or is checked. This can be fixed with a caching system. I'll be implementing one soon.

**Comment by jjacobson** [comment]
Why wouldn't you run sql queries in a separate thread?

**Comment by niccholaspage** [comment]
Fixed by using a caching system in the latest development builds.
