### ISSUE TITLE
Console command: "money <name>" not functional

### ISSUE THREAD

**Issue by TnTBass** [niccholaspage/Fe#16]
### When running the command "money [name]" from the console, the Fe help menu gets presented, not the players account balance.

**Steps to reproduce:**
Run: "money [player name]" from the console

**Expected output:**
Player balance

**Actual output:**
Fe Help.

**Version:**
Fe version 0.7-SNAPSHOT

Note: You should probably attach the build number to that version string, so problems being reported have as much accurate information as possible.

**Comment by niccholaspage** [comment]
This is a simple fix. Using the console sends the default command help instead of balance to stop people in  the console just typing /money and getting an error. I'll fix this soon.
