### ISSUE TITLE
Names with spaces (is needed for towny)

### ISSUE THREAD

**Issue by orgiz** [niccholaspage/Fe#17]
Names with spaces is needed to support town name. Now I got to manually add them in mySQL to display them online.

Hope you can do anithing about this :)

Best regards
Orgiz

**Comment by niccholaspage** [comment]
Are you requesting the ability to use names with spaces in commands so players can check money or send money to them? If so, I can do this.

**Comment by orgiz** [comment]
The problem occurs when someone on my server creats a town with a space in it.

When that happans, Fe wont create a new "town account" i my mySQL database.

Exemple:
/town new GreatBritain  <- That works, and Fe will create a new account.

/town new Great Britain <- This does not work, Fe will not recognize it and wont create the row in mySQL

**Comment by niccholaspage** [comment]
Interesting. I'll see what I can do as this may fix a problem with Factions
too.

**Comment by WoAnerges** [comment]
it's not a space, it only shows up as a space, but in reality, it's underline ("_"). Towny translates underlines into spaces, so the town "My_Town" looks like "My Town", and by vault it is recognized as "town-My_town", as far as I remember. Ask ElgarL for more info, or check the towny's source code on github.
