### ISSUE TITLE
Remove libraries from repository, use maven

### ISSUE THREAD

**Issue by riking** [niccholaspage/Fe#20]
Please use a Maven pom.xml for dependency updating; including library files makes the time and resources it takes for someone to download and use your source extremely high.

The download size of your repository is **44 megabytes**... for context, the history of CraftBukkit is only **7.4 megabytes**.

I suggest using something like `git filter-branch` to purge the `lib/` folder from the project history. You should do this now, as you only have 6 forks.

If you need assistance creating a pom.xml, I will be glad to help.

**Comment by niccholaspage** [comment]
Thanks for the help - I'll put something in the README stating the dependencies until I get a pom.xml setup.
