### ISSUE TITLE
Conversion from Fe's SQLite and MySQL databases

### ISSUE THREAD

**Issue by EdyTheCow** [niccholaspage/Fe#26]
As it says in 0.6 version:
"Add in conversion from Fe's SQLite and MySQL databases"
Does this mean I can convert from Fe MySQL to SQLite? If so, how do I do that? As I can't find any info about this.

**Comment by niccholaspage** [comment]
/fe convert fe mysql
That command will convert your MySQL database to SQLite. Your current database type has to be flat file and your config section for MySQL needs to be correct.

**Comment by bloggy** [comment]
/fe convert fe mysql 
does not work anymore -.-

**Comment by niccholaspage** [comment]
The new development build of Fe does not have conversion support. Try using the Vault convert command.
