### ISSUE TITLE
Fe is failing with the new 1.6.2?

### ISSUE THREAD

**Issue by WoAnerges** [niccholaspage/Fe#28]
I have opened a ticket in the chestshop thread, but Acrobot closed it pointing out that this is the Fe-economy fault.

http://dev.bukkit.org/bukkit-plugins/chestshop/tickets/696-severe-could-not-pass-event-currency-check-event-to/

Can you fix this problem?

**Comment by niccholaspage** [comment]
Should be fixed with the new dev builds.
