### ISSUE TITLE
Adding Auto-payment System

### ISSUE THREAD

**Issue by S3kshUn** [niccholaspage/Fe#31]
I would very much appreciate it if this plugin could have a configuration file in which you could set payment groups, which would automatically receive a configurable amount of [currency] periodically after a configurable amount of time. Each player could be assigned to these payment groups via in-game (Or in-console) commands.
Commands could be similar to: 
/fe allowance player [username] [payment group]
/fe allowance group create [groupname] [payment] [period]
/fe allowance group delete [groupname]
 "         "       modify [groupname] [payment/period]
 "         "       paynow (Forces payment on all pending groups, maybe with a confirm command).

**Comment by niccholaspage** [comment]
Its better that a more feature full plugin would do this sort of thing. Using a quick BukkitDev search, I found RankPay:
http://dev.bukkit.org/bukkit-plugins/rank-pay/
