### ISSUE TITLE
Importing from Essentials does not create user accounts

### ISSUE THREAD

**Issue by ProsperCraft** [niccholaspage/Fe#39]
I have 1868 users in essentials economy, using the Feb 7th build #56 the import runs and says conversion succeeded, but does not create any accounts, it just credits any accounts that are already in with the essentials balances.

**Comment by ProsperCraft** [comment]
On further use...this build can't write to the database, but the old release version can.

it creates the table but  will not write to it.

> fe create SugarGal
> 2014-03-17 17:45:12 [WARNING] Unexpected exception while parsing console command "fe create SugarGal"
> org.bukkit.command.CommandException: Unhandled exception executing command 'fe' in plugin Fe v0.8-SNAPSHOT
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
>         at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:533)
>         at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchServerCommand(CraftServer.java:514)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:374)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
>         at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
> Caused by: java.lang.NullPointerException
>         at org.melonbrew.fe.database.databases.SQLDB.loadAccountMoney(SQLDB.java:189)
>         at org.melonbrew.fe.database.Database.getAccount(Database.java:44)
>         at org.melonbrew.fe.database.Database.accountExists(Database.java:70)
>         at org.melonbrew.fe.API.accountExists(API.java:81)
>         at org.melonbrew.fe.command.commands.CreateCommand.onCommand(CreateCommand.java:26)
>         at org.melonbrew.fe.FeCommand.onCommand(FeCommand.java:123)
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>         ... 8 more

**Comment by niccholaspage** [comment]
Try using Vault's conversion command.
