### ISSUE TITLE
UUID Support

### ISSUE THREAD

**Issue by xfractured** [niccholaspage/Fe#44]
The upcoming release of 1.7.6 (and above) will be using UUIDs instead of player names since Mojang will be adding the ability to change player names soon.

It is very important that Fe implements this as soon as possible to prevent any issues from arising.

http://forums.bukkit.org/threads/psa-the-switch-to-uuids-potential-plugin-server-breakage.250915/

**Comment by niccholaspage** [comment]
UUID support added in commits 0a5fc4eaab187923011c86c3de1046bd09e4b405 to c307fbafce528b111eb24ae7f1d32bf0abc96072.
