### ISSUE TITLE
Bug: Sync error in multi-server setup (Build #51)

### ISSUE THREAD

**Issue by Farsinuce** [niccholaspage/Fe#57]
The issue:
Commands like "/fe grant [player] [amount]" do not work as intended in a multi-server setup using MySQL, when that user is not online on that server.

Fe version:
Build #51 (Jun 17, 2014).

Explanation:
I have servers running in a Bungeecord setup. With Enjins Donation Craft, users make purchases that will then execute commands through CommandSync in-game.

In this case, [player1] is online at [survivalServer], and buys something from DonationCraft. DonationCraft is then set to execute the command "/fe grant [player1] [amount]" on [hubServer].*

The database seems to update correctly, but on [survivalServer] the player's money have not synced - checked by using the /money command. When the player switches from [survivalServer] to [hubServer], where the Fe grant command was just issued, the database money value is then overwritten with the player's old amount instead of syncing and adding the newly purchased amount.

This is currently working in the old Fe v0.7 (Sep 04, 2013) in the same setup.

*Ethics: No, the player is not buying in-game valuta for real money.

Best regards,
Sinuce

**Comment by ferdl9999** [comment]
Hi,

i had the same issue. I fixed that whilst disabled the cache function in the config

**Comment by Farsinuce** [comment]
Thanks, I will try that and report back whether it works.

UPDATE:
Disabling the cache function works. Thanks a lot, ferdl9999!
I will leave this issue open for an administrator to decide if it should be closed.

**Comment by niccholaspage** [comment]
Yeah, the cacheaccounts function has to be disabled for a multi-server economy to work. It might be fixed later but until then, you need to keep it disabled on both servers.
